---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  labels:
    app: api
spec:
  type: ClusterIP
  #clusterIP: None
  selector:
    app: api
  ports:
    - name: http-http
      protocol: TCP
      port: 80
      targetPort: 8080
