---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jke-1-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/ping"
        backend:
          service:
            name: api-svc
            port:
              number: 80
