apiVersion: v1
kind: Namespace
metadata:
  name: api-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-ksa
  namespace: api-ns
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api-svc
  namespace: api-ns
spec:
  ports:
  - name: http-api
    nodePort: 30008
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
  namespace: api-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: api:0.0.1
        name: api
        ports:
        - containerPort: 8080
          name: http-api
      serviceAccountName: api-ksa
