apiVersion: v1
kind: Namespace
metadata:
  name: server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: server-ksa
  namespace: server
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: server-svc
  namespace: server
spec:
  ports:
  - name: http-server
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: server
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
  namespace: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: server:0.0.3
        name: server
        ports:
        - containerPort: 8080
          name: http-server
      serviceAccountName: server-ksa

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: server
  name: server-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: server-svc
            port:
              number: 80
